Description: >
    Samad Arshad / Udacity AWS Devops Project 2

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            AccessControl: Private

    S3BucketReadRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                    Service:
                    - ec2.amazonaws.com
                  Action:
                    - sts:AssumeRole
            Path: /
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

Outputs:
    S3Bucket: 
        Description: ID of the S3 Bucket
        Value: !Ref S3Bucket
        Export:
            Name: !Sub ${EnvironmentName}-S3-BUCKET
    S3BucketReadRole: 
        Description: ID of the S3 Bucket Read Role
        Value: !Ref S3BucketReadRole
        Export:
            Name: !Sub ${EnvironmentName}-S3-IAM-ROLE